<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('posts', function (Blueprint $table) {
            $table->id(); // automatically a primary key. generated by laravel.
            $table->string('title')->comment('Title of a post.'); //comment explains what the field 'title' is for. this is optional but a good habit. -> means chaining
            $table->text('content')->comment('Content of a post.');
            $table->string('slug')->comment('URL identifier of a post.');
            $table->timestamp('publication_date')->nullable(); // timestamps is a function. timestamp denotes that it is a type only.
            $table->timestamp('last_modified_date')->nullable();
            $table->string('status')->comment('D - Draft, P - Published, I - Inactive');
            $table->text('featured_image_url')->comment('URL of featured image');
            $table->integer('views_count')->default(0);
            // timestamps() are generated by laravel.
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('posts');
    }
};
